name: Control de Tareas con Bot de Discord

on:
  push:
    paths:
      - 'tareas/**'

jobs:
  notificar-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Este paso identifica cuál fue el archivo de tarea que se acaba de subir
      - name: Detectar archivo de tarea nuevo
        id: detectar
        run: |
          ARCHIVO_NUEVO=$(git diff --name-only HEAD~1 HEAD | grep '^tareas/' | head -n 1)
          echo "archivo=$ARCHIVO_NUEVO" >> $GITHUB_OUTPUT

      # Aquí corre el ejemplo de Discord que encontraste para leer y publicar el archivo completo
      - name: Discord Courier
        uses: snorrwe/discord-action@v1.0.10
        with:
          discord_token: ${{ secrets.DISCORD_BOT_TOKEN }}
          discord_channel: "1524568941890896002"
          post_file: "${{ steps.detectar.outputs.archivo }}"
